//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VC6.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VC6_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CN_COMM              129
#define IDD_DIALOG_DCB                  133
#define IDD_DIALOG_TIMEOUTS             134
#define IDI_ICON_OFF                    140
#define IDI_ICON_ON                     141
#define IDD_DIALOG_PROPERTIES           143
#define IDC_BUTTON1                     1000
#define IDC_BUTTON_NEW_INSTANCE         1000
#define IDC_TAB                         1001
#define IDC_BUTTON_FREE_INSTANCE        1002
#define IDC_EDIT_RX                     1003
#define IDC_COMBO_COM_PORT              1004
#define IDC_COMBO_PARITY                1005
#define IDC_COMBO_BAUDRATE              1006
#define IDC_COMBO_BITSSIZE              1007
#define IDC_COMBO_STOPBITS              1008
#define IDC_BUTTON_OPEN                 1009
#define IDC_BUTTON_CLEAR_RX             1010
#define IDC_EDIT_TX                     1011
#define IDC_BUTTON_SEND                 1012
#define IDC_BUTTON_CLEAR_TX             1013
#define IDC_CHECK_HEX                   1014
#define IDC_CHECK_TX_HEX                1014
#define IDC_EDIT_CYCLE                  1015
#define IDC_CHECK_AUTO_SEND             1016
#define IDC_EDIT_RX_COUNT               1017
#define IDC_EDIT_TX_COUNT               1018
#define IDC_CHECK_EN_THREAD             1019
#define IDC_CHECK_EN_OVERLAPPED         1020
#define IDC_CHECK_EN_TX_BUFFER          1021
#define IDC_CHECK_EN_RX_BUFFER          1022
#define IDC_CHECK_EN_TX_THREAD          1023
#define IDC_CHECK_EN_RX_THREAD          1024
#define IDC_COMBO_FLOW_CTRL             1025
#define IDC_CHECK_RX_HEX                1026
#define IDC_EDIT_RX_QUEUE               1027
#define IDC_EDIT_TX_QUEUE               1028
#define IDC_BUTTON_RESET                1029
#define IDC_EDIT_RX_BUFFER              1030
#define IDC_EDIT_DCBlength              1031
#define IDC_EDIT_TX_BUFFER              1031
#define IDC_EDIT_BaudRate               1032
#define IDC_EDIT_fBinary                1033
#define IDC_EDIT_fParity                1034
#define IDC_EDIT_fOutxCtsFlow           1035
#define IDC_EDIT_fDtrControl            1036
#define IDC_EDIT_fDsrSensitivity        1037
#define IDC_EDIT_fTXContinueOnXoff      1038
#define IDC_EDIT_fOutX                  1039
#define IDC_EDIT_fInX                   1040
#define IDC_EDIT_fErrorChar             1041
#define IDC_EDIT_fNull                  1042
#define IDC_EDIT_fRtsControl            1043
#define IDC_EDIT_fAbortOnError          1044
#define IDC_EDIT_fDummy2                1045
#define IDC_EDIT_wReserved              1046
#define IDC_EDIT_XonLim                 1047
#define IDC_EDIT_XoffLim                1048
#define IDC_EDIT_ByteSize               1049
#define IDC_BUTTON_SET                  1050
#define IDC_EDIT_dwCallSetupFailTimer   1050
#define IDC_EDIT_Parity                 1051
#define IDC_EDIT_StopBits               1052
#define IDC_EDIT_XonChar                1053
#define IDC_EDIT_XoffChar               1054
#define IDC_EDIT_dwInactivityTimeout    1055
#define IDC_EDIT_dwSpeakerVolume        1056
#define IDC_EDIT_dwSpeakerMode          1057
#define IDC_EDIT_dwModemOptions         1058
#define IDC_EDIT_ErrorChar              1067
#define IDC_EDIT_EofChar                1068
#define IDC_EDIT_EvtChar                1069
#define IDC_EDIT_wReserved1             1070
#define IDC_EDIT_dwMaxDTERate           1071
#define IDC_EDIT_dwMaxDCERate           1072
#define IDC_EDIT_dwModemVersionSize     1073
#define IDC_BUTTON_DCB                  1089
#define IDC_BUTTON_SEND_FILE            1090
#define IDC_EDIT1                       1091
#define IDC_EDIT_FILE_FOR_SEND          1091
#define IDC_BUTTON_BROWER               1092
#define IDC_BUTTON_BROWER_TX            1092
#define IDC_BUTTON_LOAD_FILE            1093
#define IDC_CHECK_DTR                   1094
#define IDC_CHECK_BREAK                 1095
#define IDC_CHECK_RTS                   1096
#define IDC_CHECK4                      1097
#define IDC_CHECK_XON                   1097
#define IDC_CHECK_RLSD                  1098
#define IDC_CHECK6                      1099
#define IDC_CHECK_RING                  1099
#define IDC_CHECK7                      1100
#define IDC_CHECK_DSR                   1100
#define IDC_CHECK_CTS                   1101
#define IDC_BUTTON2                     1102
#define IDC_BUTTON_SAVE                 1102
#define IDC_BUTTON3                     1103
#define IDC_BUTTON_BROWER_RX            1103
#define IDC_BUTTON_TIMEOUTS             1104
#define IDC_BUTTON_PROPERTIES           1105
#define IDC_EDIT_RIT                    1106
#define IDC_EDIT_FILE_FOR_RECV          1106
#define IDC_EDIT_RTTM                   1107
#define IDC_EDIT_RTTC                   1108
#define IDC_EDIT_WTTM                   1109
#define IDC_EDIT_WTTC                   1110
#define IDC_STATIC_LAMP                 1116
#define IDC_EDIT_wPacketLength          1117
#define IDC_EDIT_wPacketVersion         1118
#define IDC_EDIT_dwServiceMask          1119
#define IDC_EDIT_dwMaxTxQueue           1121
#define IDC_EDIT_dwMaxRxQueue           1122
#define IDC_EDIT_dwMaxBaud              1123
#define IDC_EDIT_dwProvSubType          1124
#define IDC_EDIT_dwProvCapabilities     1125
#define IDC_EDIT_dwSettableParams       1126
#define IDC_EDIT_dwSettableBaud         1127
#define IDC_EDIT_wSettableData          1128
#define IDC_EDIT_wSettableStopParity    1129
#define IDC_EDIT_dwCurrentTxQueue       1130
#define IDC_EDIT_dwCurrentRxQueue       1131
#define IDC_EDIT_dwProvSpec1            1132
#define IDC_EDIT_dwProvSpec2            1133
#define IDC_EDIT_dwRequiredSize         1134
#define IDC_EDIT_dwDevSpecificOffset    1135
#define IDC_EDIT_dwDevSpecificSize      1136
#define IDC_EDIT_dwModemProviderVersion 1137
#define IDC_EDIT_dwModemManufacturerOffset 1138
#define IDC_EDIT_dwModemManufacturerSize 1139
#define IDC_EDIT_dwModemModelOffset     1140
#define IDC_EDIT_dwModemModelSize       1141
#define IDC_EDIT_dwModemVersionOffset   1142
#define IDC_EDIT_dwDialOptions          1143
#define IDC_CHECK_DISP                  1145
#define IDC_CHECK_SAVE                  1146
#define IDC_STATIC_RX                   1148
#define IDC_STATIC_TX                   1149
#define IDC_STATIC_MAIL                 1151
#define IDC_STATIC_BLOG1                1152
#define IDC_STATIC_BLOG2                1153

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1154
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
